// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Cadastro.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace src.protobuf.generatedClasses {

  /// <summary>Holder for reflection information generated from Cadastro.proto</summary>
  public static partial class CadastroReflection {

    #region Descriptor
    /// <summary>File descriptor for Cadastro.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CadastroReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5DYWRhc3Ryby5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5w",
            "cm90byKqAgoIQ2FkYXN0cm8SIwoIQ2xpZW50ZXMYASADKAsyES5DYWRhc3Ry",
            "by5DbGllbnRlGvgBCgdDbGllbnRlEhMKC1ByaW1lcm9Ob21lGAEgASgJEhIK",
            "ClVsdGltb05vbWUYAiABKAkSMgoORGF0YU5hc2NpbWVudG8YAyABKAsyGi5n",
            "b29nbGUucHJvdG9idWYuVGltZXN0YW1wEi0KCUVuZGVyZWNvcxgEIAMoCzIa",
            "LkNhZGFzdHJvLkNsaWVudGUuRW5kZXJlY28aYQoIRW5kZXJlY28SEgoKTG9n",
            "cmFkb3VybxgBIAEoCRITCgtDb21wbGVtZW50bxgCIAEoCRIOCgZCYWlycm8Y",
            "AyABKAkSDgoGQ2lkYWRlGAQgASgJEgwKBFBhaXMYBSABKAlCIKoCHXNyYy5w",
            "cm90b2J1Zi5nZW5lcmF0ZWRDbGFzc2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::src.protobuf.generatedClasses.Cadastro), global::src.protobuf.generatedClasses.Cadastro.Parser, new[]{ "Clientes" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::src.protobuf.generatedClasses.Cadastro.Types.Cliente), global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Parser, new[]{ "PrimeroNome", "UltimoNome", "DataNascimento", "Enderecos" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco), global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco.Parser, new[]{ "Logradouro", "Complemento", "Bairro", "Cidade", "Pais" }, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Cadastro : pb::IMessage<Cadastro> {
    private static readonly pb::MessageParser<Cadastro> _parser = new pb::MessageParser<Cadastro>(() => new Cadastro());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Cadastro> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::src.protobuf.generatedClasses.CadastroReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cadastro() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cadastro(Cadastro other) : this() {
      clientes_ = other.clientes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cadastro Clone() {
      return new Cadastro(this);
    }

    /// <summary>Field number for the "Clientes" field.</summary>
    public const int ClientesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente> _repeated_clientes_codec
        = pb::FieldCodec.ForMessage(10, global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Parser);
    private readonly pbc::RepeatedField<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente> clientes_ = new pbc::RepeatedField<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente> Clientes {
      get { return clientes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Cadastro);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Cadastro other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!clientes_.Equals(other.clientes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= clientes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      clientes_.WriteTo(output, _repeated_clientes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += clientes_.CalculateSize(_repeated_clientes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Cadastro other) {
      if (other == null) {
        return;
      }
      clientes_.Add(other.clientes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            clientes_.AddEntriesFrom(input, _repeated_clientes_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Cadastro message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Cliente : pb::IMessage<Cliente> {
        private static readonly pb::MessageParser<Cliente> _parser = new pb::MessageParser<Cliente>(() => new Cliente());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Cliente> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::src.protobuf.generatedClasses.Cadastro.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Cliente() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Cliente(Cliente other) : this() {
          primeroNome_ = other.primeroNome_;
          ultimoNome_ = other.ultimoNome_;
          dataNascimento_ = other.dataNascimento_ != null ? other.dataNascimento_.Clone() : null;
          enderecos_ = other.enderecos_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Cliente Clone() {
          return new Cliente(this);
        }

        /// <summary>Field number for the "PrimeroNome" field.</summary>
        public const int PrimeroNomeFieldNumber = 1;
        private string primeroNome_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string PrimeroNome {
          get { return primeroNome_; }
          set {
            primeroNome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "UltimoNome" field.</summary>
        public const int UltimoNomeFieldNumber = 2;
        private string ultimoNome_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string UltimoNome {
          get { return ultimoNome_; }
          set {
            ultimoNome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "DataNascimento" field.</summary>
        public const int DataNascimentoFieldNumber = 3;
        private global::Google.Protobuf.WellKnownTypes.Timestamp dataNascimento_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Protobuf.WellKnownTypes.Timestamp DataNascimento {
          get { return dataNascimento_; }
          set {
            dataNascimento_ = value;
          }
        }

        /// <summary>Field number for the "Enderecos" field.</summary>
        public const int EnderecosFieldNumber = 4;
        private static readonly pb::FieldCodec<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco> _repeated_enderecos_codec
            = pb::FieldCodec.ForMessage(34, global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco.Parser);
        private readonly pbc::RepeatedField<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco> enderecos_ = new pbc::RepeatedField<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Types.Endereco> Enderecos {
          get { return enderecos_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Cliente);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Cliente other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (PrimeroNome != other.PrimeroNome) return false;
          if (UltimoNome != other.UltimoNome) return false;
          if (!object.Equals(DataNascimento, other.DataNascimento)) return false;
          if(!enderecos_.Equals(other.enderecos_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (PrimeroNome.Length != 0) hash ^= PrimeroNome.GetHashCode();
          if (UltimoNome.Length != 0) hash ^= UltimoNome.GetHashCode();
          if (dataNascimento_ != null) hash ^= DataNascimento.GetHashCode();
          hash ^= enderecos_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (PrimeroNome.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(PrimeroNome);
          }
          if (UltimoNome.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(UltimoNome);
          }
          if (dataNascimento_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(DataNascimento);
          }
          enderecos_.WriteTo(output, _repeated_enderecos_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (PrimeroNome.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(PrimeroNome);
          }
          if (UltimoNome.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(UltimoNome);
          }
          if (dataNascimento_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataNascimento);
          }
          size += enderecos_.CalculateSize(_repeated_enderecos_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Cliente other) {
          if (other == null) {
            return;
          }
          if (other.PrimeroNome.Length != 0) {
            PrimeroNome = other.PrimeroNome;
          }
          if (other.UltimoNome.Length != 0) {
            UltimoNome = other.UltimoNome;
          }
          if (other.dataNascimento_ != null) {
            if (dataNascimento_ == null) {
              DataNascimento = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            DataNascimento.MergeFrom(other.DataNascimento);
          }
          enderecos_.Add(other.enderecos_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                PrimeroNome = input.ReadString();
                break;
              }
              case 18: {
                UltimoNome = input.ReadString();
                break;
              }
              case 26: {
                if (dataNascimento_ == null) {
                  DataNascimento = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(DataNascimento);
                break;
              }
              case 34: {
                enderecos_.AddEntriesFrom(input, _repeated_enderecos_codec);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Cliente message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public sealed partial class Endereco : pb::IMessage<Endereco> {
            private static readonly pb::MessageParser<Endereco> _parser = new pb::MessageParser<Endereco>(() => new Endereco());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<Endereco> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::src.protobuf.generatedClasses.Cadastro.Types.Cliente.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Endereco() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Endereco(Endereco other) : this() {
              logradouro_ = other.logradouro_;
              complemento_ = other.complemento_;
              bairro_ = other.bairro_;
              cidade_ = other.cidade_;
              pais_ = other.pais_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Endereco Clone() {
              return new Endereco(this);
            }

            /// <summary>Field number for the "Logradouro" field.</summary>
            public const int LogradouroFieldNumber = 1;
            private string logradouro_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Logradouro {
              get { return logradouro_; }
              set {
                logradouro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "Complemento" field.</summary>
            public const int ComplementoFieldNumber = 2;
            private string complemento_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Complemento {
              get { return complemento_; }
              set {
                complemento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "Bairro" field.</summary>
            public const int BairroFieldNumber = 3;
            private string bairro_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Bairro {
              get { return bairro_; }
              set {
                bairro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "Cidade" field.</summary>
            public const int CidadeFieldNumber = 4;
            private string cidade_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Cidade {
              get { return cidade_; }
              set {
                cidade_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "Pais" field.</summary>
            public const int PaisFieldNumber = 5;
            private string pais_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Pais {
              get { return pais_; }
              set {
                pais_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as Endereco);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(Endereco other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Logradouro != other.Logradouro) return false;
              if (Complemento != other.Complemento) return false;
              if (Bairro != other.Bairro) return false;
              if (Cidade != other.Cidade) return false;
              if (Pais != other.Pais) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (Logradouro.Length != 0) hash ^= Logradouro.GetHashCode();
              if (Complemento.Length != 0) hash ^= Complemento.GetHashCode();
              if (Bairro.Length != 0) hash ^= Bairro.GetHashCode();
              if (Cidade.Length != 0) hash ^= Cidade.GetHashCode();
              if (Pais.Length != 0) hash ^= Pais.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (Logradouro.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Logradouro);
              }
              if (Complemento.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Complemento);
              }
              if (Bairro.Length != 0) {
                output.WriteRawTag(26);
                output.WriteString(Bairro);
              }
              if (Cidade.Length != 0) {
                output.WriteRawTag(34);
                output.WriteString(Cidade);
              }
              if (Pais.Length != 0) {
                output.WriteRawTag(42);
                output.WriteString(Pais);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (Logradouro.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Logradouro);
              }
              if (Complemento.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Complemento);
              }
              if (Bairro.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Bairro);
              }
              if (Cidade.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Cidade);
              }
              if (Pais.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Pais);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(Endereco other) {
              if (other == null) {
                return;
              }
              if (other.Logradouro.Length != 0) {
                Logradouro = other.Logradouro;
              }
              if (other.Complemento.Length != 0) {
                Complemento = other.Complemento;
              }
              if (other.Bairro.Length != 0) {
                Bairro = other.Bairro;
              }
              if (other.Cidade.Length != 0) {
                Cidade = other.Cidade;
              }
              if (other.Pais.Length != 0) {
                Pais = other.Pais;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Logradouro = input.ReadString();
                    break;
                  }
                  case 18: {
                    Complemento = input.ReadString();
                    break;
                  }
                  case 26: {
                    Bairro = input.ReadString();
                    break;
                  }
                  case 34: {
                    Cidade = input.ReadString();
                    break;
                  }
                  case 42: {
                    Pais = input.ReadString();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
